name: Build, Test, and Deploy .NET 9 Web API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore MyAutomationSolution.sln

      - name: Build
        run: dotnet build MyAutomationSolution.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test MyAutomationSolution.sln --configuration Release --no-build --verbosity normal

    # Deployment step (optional, if you want Azure or any hosting)
